projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: https://standupin-dev.herokuapp.com/prisma-db/dev

  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: src/generated/prisma.ts