service: standupin-api

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  include:
    - src/**
    - .graphqlconfig

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs8.10
  timeout: 30 # The default is 6 seconds. Note: API Gateway current maximum is 30 seconds

  environment: # Service wide environment variables
    SCRAPER_FUNCTION_NAME: ${self:service}-${self:provider.stage}-scrape
    PRISMA_MANAGEMENT_API_SECRET: ${env:PRISMA_MANAGEMENT_API_SECRET}
    PRISMA_ENDPOINT: ${env:PRISMA_ENDPOINT}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"

functions:
  graphql:
    handler: handler.server
    events:
    - http:
        path: /
        method: post
        cors: true
  playground:
    handler: handler.playground
    timeout: 30 # The default is 6 seconds. Note: API Gateway current maximum is 30 seconds
    events:
    - http:
        path: /
        method: get
        cors: true
  scrape:
    handler: scraper.scrape
    timeout: 300
    # events:
    # - schedule: rate(5 minutes)

  cron_launcher:
    timeout: 300
    handler: scraper.cron
    events:
      - schedule: rate(5 minutes)
