service: yoga-example-four

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  include:
    - src/**
    - .graphqlconfig

provider:
  name: aws
  runtime: nodejs6.10
  environment: # Service wide environment variables
    PRISMA_MANAGEMENT_API_SECRET: ***REMOVED***
    PRISMA_ENDPOINT: ***REMOVED***

functions:
  graphql:
    handler: handler.server
    events:
    - http:
        path: /
        method: post
        cors: true
  playground:
    handler: handler.playground
    timeout: 30 # The default is 6 seconds. Note: API Gateway current maximum is 30 seconds
    events:
    - http:
        path: /
        method: get
        cors: true
